# Generated by Django 5.0.6 on 2024-07-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Hotel Name')),
                ('city', models.IntegerField(choices=[(1, 'Delhi'), (2, 'Pune'), (3, 'Bangalore'), (4, 'Mumbai')], verbose_name='City')),
                ('price', models.IntegerField()),
                ('pimage', models.ImageField(upload_to='image')),
            ],
        ),
    ]
