# Generated by Django 5.0.6 on 2024-08-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayapp', '0003_product_checkin_product_checkout_product_para_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
