# Generated by Django 5.0.6 on 2024-08-01 09:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayapp', '0004_product_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total',
        ),
        migrations.AddField(
            model_name='booked',
            name='checkin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booked',
            name='checkout',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booked',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
