# Generated by Django 5.0.6 on 2024-08-01 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stayapp', '0005_remove_product_checkin_remove_product_checkout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked',
            name='total',
        ),
    ]
