# Generated by Django 5.0.6 on 2024-08-01 10:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stayapp', '0006_remove_booked_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booked',
            new_name='Cart',
        ),
    ]
