# Generated by Django 5.0.6 on 2024-08-06 07:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayapp', '0008_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='checkin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cart',
            name='checkout',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
