# Generated by Django 5.0.6 on 2024-09-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stayapp', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
