# Generated by Django 5.0.6 on 2024-09-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stayapp', '0014_auth_user_delete_profile'),
    ]

    # operations = [
    #     migrations.RenameField(
    #         model_name='auth_user',
    #         old_name='mobile_number',
    #         new_name='mobile_no',
    #     ),
    # ]
