# Generated by Django 5.0.6 on 2024-09-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stayapp', '0015_rename_mobile_number_auth_user_mobile_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auth_user',
        ),
    ]
